import { FlashCard } from './types';

export const mockCards: FlashCard[] = [
  {
    id: 1,
    total: 36,
    tags: ['Opening', 'Theory'],
    question: "What is the best continuation for White in the Queen's Gambit Accepted?",
    positionDescription: 'Position after 1.d4 d5 2.c4 dxc4 3.Nf3 Nf6',
    tip: 'Tip: Control the center and develop harmoniously.',
    boardFen: 'rnbqkb1r/ppp1pppp/5n2/8/2pP4/5N2/PP2PPPP/RNBQKB1R w KQkq - 2 4',
    correctMove: '4.e3',
    correctMoveFrom: 'e2',
    correctMoveTo: 'e3',
    correctMoveAlgebraic: 'e2–e3',
    evaluation: '+0.25',
    explanation: '4.e3 is the main line, supporting the d4 pawn and developing the light-squared bishop. White aims for a strong center and long-term pressure.',
    idea: 'White claims space in the center and prepares development with Bg5 or Bd3, while keeping flexibility.',
    moveOrder: [
      { white: 'd4', black: 'd5' },
      { white: 'c4', black: 'dxc4' },
      { white: 'Nf3', black: 'Nf6' },
      { white: 'e3', black: 'e6' },
      { white: 'Bxc4', black: 'Bd6' },
      { white: 'O-O', black: 'O-O' },
      { white: 'Nc3', black: 'c6' },
    ],
    highlightSquares: ['e2', 'e3'],
    currentMoveIndex: 3,
  },
  {
    id: 2,
    total: 36,
    tags: ['Gambit', 'Tactics'],
    question: "What is the critical response after 1.e4 e5 2.Nf3 Nc6 3.Bc4 in the Italian Game?",
    positionDescription: 'Position after 1.e4 e5 2.Nf3 Nc6 3.Bc4',
    tip: 'Tip: Consider controlling the center with a pawn push.',
    boardFen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3',
    correctMove: '3...Bc5',
    correctMoveFrom: 'f8',
    correctMoveTo: 'c5',
    correctMoveAlgebraic: 'f8–c5',
    evaluation: '+0.10',
    explanation: "3...Bc5 enters the Giuoco Piano, developing naturally and eyeing f2. This is Black's most classical response.",
    idea: "Black mirrors White's setup, aiming for solid development and eventual central counterplay.",
    moveOrder: [
      { white: 'e4', black: 'e5' },
      { white: 'Nf3', black: 'Nc6' },
      { white: 'Bc4', black: 'Bc5' },
      { white: 'c3', black: 'Nf6' },
      { white: 'd4', black: 'exd4' },
      { white: 'cxd4', black: 'Bb4+' },
    ],
    highlightSquares: ['f8', 'c5'],
    currentMoveIndex: 2,
  },
  {
    id: 3,
    total: 36,
    tags: ['Tactics', 'Endgame'],
    question: "Find the winning tactic for White — mate in 2.",
    positionDescription: 'White to move and checkmate in 2 moves',
    tip: 'Tip: Look for a forcing sequence that restricts the king.',
    boardFen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
    correctMove: '1.Re8#',
    correctMoveFrom: 'e1',
    correctMoveTo: 'e8',
    correctMoveAlgebraic: 'e1–e8',
    evaluation: '+M2',
    explanation: '1.Re8# delivers immediate checkmate. The rook slides to the eighth rank where the king has no escape.',
    idea: 'Rook lift to the back rank forces checkmate immediately with no defensive resources.',
    moveOrder: [{ white: 'Re8#', black: '' }],
    highlightSquares: ['e1', 'e8'],
    currentMoveIndex: 0,
  },
];

export const activityData = [
  [false, false, false, true, false, false, false],
  [false, false, false, false, true, false, false],
  [true, false, true, true, false, false, false],
  [false, false, false, false, false, false, false],
];
