import { FlashCard, ImportedOpeningLine, OpeningNoteStore, OpeningProgressMap, OpeningRepertoire } from './types';

export const mockCards: FlashCard[] = [
  {
    id: 1,
    total: 36,
    tags: ['Opening', 'Theory'],
    question: "What is the best continuation for White in the Queen's Gambit Accepted?",
    positionDescription: 'Position after 1.d4 d5 2.c4 dxc4 3.Nf3 Nf6',
    tip: 'Tip: Control the center and develop harmoniously.',
    boardFen: 'rnbqkb1r/ppp1pppp/5n2/8/2pP4/5N2/PP2PPPP/RNBQKB1R w KQkq - 2 4',
    correctMove: '4.e3',
    correctMoveFrom: 'e2',
    correctMoveTo: 'e3',
    correctMoveAlgebraic: 'e2–e3',
    evaluation: '+0.25',
    explanation: '4.e3 is the main line, supporting the d4 pawn and developing the light-squared bishop. White aims for a strong center and long-term pressure.',
    idea: 'White claims space in the center and prepares development with Bg5 or Bd3, while keeping flexibility.',
    moveOrder: [
      { white: 'd4', black: 'd5' },
      { white: 'c4', black: 'dxc4' },
      { white: 'Nf3', black: 'Nf6' },
      { white: 'e3', black: 'e6' },
      { white: 'Bxc4', black: 'Bd6' },
      { white: 'O-O', black: 'O-O' },
      { white: 'Nc3', black: 'c6' },
    ],
    highlightSquares: ['e2', 'e3'],
    currentMoveIndex: 3,
  },
  {
    id: 2,
    total: 36,
    tags: ['Gambit', 'Tactics'],
    question: "What is the critical response after 1.e4 e5 2.Nf3 Nc6 3.Bc4 in the Italian Game?",
    positionDescription: 'Position after 1.e4 e5 2.Nf3 Nc6 3.Bc4',
    tip: 'Tip: Consider controlling the center with a pawn push.',
    boardFen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3',
    correctMove: '3...Bc5',
    correctMoveFrom: 'f8',
    correctMoveTo: 'c5',
    correctMoveAlgebraic: 'f8–c5',
    evaluation: '+0.10',
    explanation: "3...Bc5 enters the Giuoco Piano, developing naturally and eyeing f2. This is Black's most classical response.",
    idea: "Black mirrors White's setup, aiming for solid development and eventual central counterplay.",
    moveOrder: [
      { white: 'e4', black: 'e5' },
      { white: 'Nf3', black: 'Nc6' },
      { white: 'Bc4', black: 'Bc5' },
      { white: 'c3', black: 'Nf6' },
      { white: 'd4', black: 'exd4' },
      { white: 'cxd4', black: 'Bb4+' },
    ],
    highlightSquares: ['f8', 'c5'],
    currentMoveIndex: 2,
  },
  {
    id: 3,
    total: 36,
    tags: ['Tactics', 'Endgame'],
    question: "Find the winning tactic for White — mate in 2.",
    positionDescription: 'White to move and checkmate in 2 moves',
    tip: 'Tip: Look for a forcing sequence that restricts the king.',
    boardFen: '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
    correctMove: '1.Re8#',
    correctMoveFrom: 'e1',
    correctMoveTo: 'e8',
    correctMoveAlgebraic: 'e1–e8',
    evaluation: '+M2',
    explanation: '1.Re8# delivers immediate checkmate. The rook slides to the eighth rank where the king has no escape.',
    idea: 'Rook lift to the back rank forces checkmate immediately with no defensive resources.',
    moveOrder: [{ white: 'Re8#', black: '' }],
    highlightSquares: ['e1', 'e8'],
    currentMoveIndex: 0,
  },
];

export const activityData = [
  [false, false, false, true, false, false, false],
  [false, false, false, false, true, false, false],
  [true, false, true, true, false, false, false],
  [false, false, false, false, false, false, false],
];

export const openingRepertoires: OpeningRepertoire[] = [
  {
    id: 'qga-white-main',
    name: "Queen's Gambit Accepted",
    eco: 'D20',
    side: 'White',
    family: "Queen's Gambit",
    description: 'Recover the c4 pawn with calm development and central control.',
    tags: ['Opening', 'Gambit', 'Repertoire', 'Positional'],
    totalPositions: 9,
    duePositions: 4,
    accuracy: 82,
    mastery: 56,
    root: {
      id: 'qga-4-e3',
      fen: 'rnbqkb1r/ppp1pppp/5n2/8/2pP4/5N2/PP2PPPP/RNBQKB1R w KQkq - 2 4',
      moveNumber: 4,
      sideToMove: 'w',
      prompt: 'Stabilize the center before recapturing on c4.',
      expectedMoveSan: '4.e3',
      expectedMoveFrom: 'e2',
      expectedMoveTo: 'e3',
      opponentReplySan: '4...e6',
      opponentReplyFrom: 'e7',
      opponentReplyTo: 'e6',
      opponentReplyFen: 'rnbqkb1r/ppp2ppp/4pn2/8/2pP4/4PN2/PP3PPP/RNBQKB1R w KQkq - 0 5',
      idea: 'Support d4, open the bishop, and prepare to regain the gambit pawn.',
      explanation: 'White should avoid rushing. e3 keeps the structure sound and makes Bxc4 possible under better conditions.',
      tags: ['Gambit', 'Main line', 'Development'],
      branches: [
        {
          id: 'qga-e6-bxc4',
          fen: 'rnbqkb1r/ppp2ppp/4pn2/8/2pP4/4PN2/PP3PPP/RNBQKB1R w KQkq - 0 5',
          moveNumber: 5,
          sideToMove: 'w',
          incomingMoveSan: '4...e6',
          prompt: 'Black supports c4 with ...e6. Recover the pawn.',
          expectedMoveSan: '5.Bxc4',
          expectedMoveFrom: 'f1',
          expectedMoveTo: 'c4',
          opponentReplySan: '5...Bd6',
          opponentReplyFrom: 'f8',
          opponentReplyTo: 'd6',
          opponentReplyFen: 'rnbqk2r/ppp2ppp/3bpn2/8/2BP4/4PN2/PP3PPP/RNBQK2R w KQkq - 2 6',
          idea: 'Finish the opening task: regain the pawn while developing a piece.',
          explanation: 'Bxc4 restores material and places the bishop on an active diagonal toward f7.',
          tags: ['Recapture', 'Piece activity'],
          branches: [
            {
              id: 'qga-bd6-castle',
              fen: 'rnbqk2r/ppp2ppp/3bpn2/8/2BP4/4PN2/PP3PPP/RNBQK2R w KQkq - 2 6',
              moveNumber: 6,
              sideToMove: 'w',
              incomingMoveSan: '5...Bd6',
              prompt: 'Black develops actively. Get the king safe.',
              expectedMoveSan: '6.O-O',
              expectedMoveFrom: 'e1',
              expectedMoveTo: 'g1',
              idea: 'Castle before choosing the queenside development scheme.',
              explanation: 'White completes king safety and keeps Nc3, Qe2, and b3 plans available.',
              tags: ['King safety', 'Main line'],
              branches: [],
            },
          ],
        },
        {
          id: 'qga-c5-bxc4',
          fen: 'rnbqkb1r/pp2pppp/5n2/2p5/2pP4/4PN2/PP3PPP/RNBQKB1R w KQkq c6 0 5',
          moveNumber: 5,
          sideToMove: 'w',
          incomingMoveSan: '4...c5',
          prompt: 'Black challenges the center immediately with ...c5.',
          expectedMoveSan: '5.Bxc4',
          expectedMoveFrom: 'f1',
          expectedMoveTo: 'c4',
          opponentReplySan: '5...cxd4',
          opponentReplyFrom: 'c5',
          opponentReplyTo: 'd4',
          opponentReplyFen: 'rnbqkb1r/pp2pppp/5n2/8/2Bp4/4PN2/PP3PPP/RNBQK2R w KQkq - 0 6',
          idea: 'Recover the pawn and prepare to meet central tension directly.',
          explanation: 'Bxc4 is still principled. White regains material and can answer ...cxd4 with exd4.',
          tags: ['Central tension', 'Recapture'],
          branches: [],
        },
      ],
    },
  },
  {
    id: 'italian-black-classical',
    name: 'Italian Game Classical',
    eco: 'C50',
    side: 'Black',
    family: 'Italian Game',
    description: 'Meet Bc4 with classical development and pressure on the center.',
    tags: ['Opening', 'Black repertoire', 'Classical'],
    totalPositions: 7,
    duePositions: 3,
    accuracy: 74,
    mastery: 42,
    root: {
      id: 'italian-bc5',
      fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3',
      moveNumber: 3,
      sideToMove: 'b',
      prompt: 'Choose the classical developing move against the Italian bishop.',
      expectedMoveSan: '3...Bc5',
      expectedMoveFrom: 'f8',
      expectedMoveTo: 'c5',
      opponentReplySan: '4.c3',
      opponentReplyFrom: 'c2',
      opponentReplyTo: 'c3',
      opponentReplyFen: 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/2P2N2/PP1P1PPP/RNBQK2R b KQkq - 0 4',
      idea: 'Develop naturally, contest the center, and keep pressure on f2.',
      explanation: 'Bc5 enters the Giuoco Piano structures and keeps Black flexible.',
      tags: ['Development', 'Classical'],
      branches: [
        {
          id: 'italian-c3-nf6',
          fen: 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/2P2N2/PP1P1PPP/RNBQK2R b KQkq - 0 4',
          moveNumber: 4,
          sideToMove: 'b',
          incomingMoveSan: '4.c3',
          prompt: 'White prepares d4. Increase pressure on the center.',
          expectedMoveSan: '4...Nf6',
          expectedMoveFrom: 'g8',
          expectedMoveTo: 'f6',
          idea: 'Attack e4 and prepare to meet d4 tactically.',
          explanation: 'Nf6 is the most direct developing move and keeps Black ready for central breaks.',
          tags: ['Center pressure', 'Development'],
          branches: [],
        },
      ],
    },
  },
  {
    id: 'kings-gambit-black',
    name: "King's Gambit Accepted",
    eco: 'C33',
    side: 'Black',
    family: "King's Gambit",
    description: 'Accept the gambit, then develop without letting White seize the initiative.',
    tags: ['Opening', 'Gambit', 'Sharp'],
    totalPositions: 7,
    duePositions: 6,
    accuracy: 68,
    mastery: 31,
    root: {
      id: 'kga-accept',
      fen: 'rnbqkbnr/pppp1ppp/8/4p3/4PP2/8/PPPP2PP/RNBQKBNR b KQkq f3 0 2',
      moveNumber: 2,
      sideToMove: 'b',
      prompt: 'White offers the f-pawn. Accept the challenge.',
      expectedMoveSan: '2...exf4',
      expectedMoveFrom: 'e5',
      expectedMoveTo: 'f4',
      opponentReplySan: '3.Nf3',
      opponentReplyFrom: 'g1',
      opponentReplyTo: 'f3',
      opponentReplyFen: 'rnbqkbnr/pppp1ppp/8/8/4Pp2/5N2/PPPP2PP/RNBQKB1R b KQkq - 1 3',
      idea: 'Take the pawn and force White to prove compensation.',
      explanation: 'Accepting the gambit is principled, but Black must develop quickly afterward.',
      tags: ['Gambit', 'Material'],
      branches: [
        {
          id: 'kga-nf3-g5',
          fen: 'rnbqkbnr/pppp1ppp/8/8/4Pp2/5N2/PPPP2PP/RNBQKB1R b KQkq - 1 3',
          moveNumber: 3,
          sideToMove: 'b',
          incomingMoveSan: '3.Nf3',
          prompt: 'White develops and attacks the f4 pawn. Hold the extra pawn with the classical thrust.',
          expectedMoveSan: '3...g5',
          expectedMoveFrom: 'g7',
          expectedMoveTo: 'g5',
          opponentReplySan: '4.h4',
          opponentReplyFrom: 'h2',
          opponentReplyTo: 'h4',
          opponentReplyFen: 'rnbqkbnr/pppp1p1p/8/6p1/4Pp1P/5N2/PPPP2P1/RNBQKB1R b KQkq h3 0 4',
          idea: 'Support f4 and make White spend tempi proving the attack.',
          explanation: 'The classical ...g5 is ambitious and thematic. It preserves the gambit pawn but creates concrete defensive responsibilities.',
          tags: ['Gambit', 'Pawn storm', 'Weak branch'],
          branches: [],
        },
      ],
    },
  },
];

export const openingProgressById: OpeningProgressMap = {
  'qga-4-e3': {
    nodeId: 'qga-4-e3',
    lastTrainedAt: '2026-06-20T14:15:00.000Z',
    nextDueAt: '2026-06-22T08:00:00.000Z',
    intervalDays: 2,
    ease: 2.35,
    lapses: 0,
    attempts: 6,
    correct: 5,
    missed: 1,
    streak: 3,
    due: true,
    lastResult: 'correct',
    lastRating: 'good',
    mastery: 68,
  },
  'qga-e6-bxc4': {
    nodeId: 'qga-e6-bxc4',
    lastTrainedAt: '2026-06-18T13:40:00.000Z',
    nextDueAt: '2026-06-21T08:00:00.000Z',
    intervalDays: 3,
    ease: 2.2,
    lapses: 1,
    attempts: 6,
    correct: 4,
    missed: 2,
    streak: 0,
    due: true,
    lastResult: 'incorrect',
    lastRating: 'again',
    mastery: 44,
  },
  'qga-bd6-castle': {
    nodeId: 'qga-bd6-castle',
    nextDueAt: '2026-06-22T08:00:00.000Z',
    intervalDays: 0,
    ease: 2.3,
    lapses: 0,
    attempts: 0,
    correct: 0,
    missed: 0,
    streak: 0,
    due: true,
    mastery: 0,
  },
  'italian-bc5': {
    nodeId: 'italian-bc5',
    lastTrainedAt: '2026-06-19T19:10:00.000Z',
    nextDueAt: '2026-06-22T08:00:00.000Z',
    intervalDays: 3,
    ease: 2.4,
    lapses: 0,
    attempts: 4,
    correct: 3,
    missed: 1,
    streak: 2,
    due: true,
    lastResult: 'correct',
    lastRating: 'hard',
    mastery: 52,
  },
  'italian-c3-nf6': {
    nodeId: 'italian-c3-nf6',
    nextDueAt: '2026-06-21T08:00:00.000Z',
    intervalDays: 0,
    ease: 2.3,
    lapses: 0,
    attempts: 0,
    correct: 0,
    missed: 0,
    streak: 0,
    due: true,
    mastery: 0,
  },
  'kga-accept': {
    nodeId: 'kga-accept',
    lastTrainedAt: '2026-06-17T11:30:00.000Z',
    nextDueAt: '2026-06-21T08:00:00.000Z',
    intervalDays: 4,
    ease: 2.1,
    lapses: 2,
    attempts: 7,
    correct: 4,
    missed: 3,
    streak: 0,
    due: true,
    lastResult: 'incorrect',
    lastRating: 'hard',
    mastery: 28,
  },
  'kga-nf3-g5': {
    nodeId: 'kga-nf3-g5',
    lastTrainedAt: '2026-06-20T21:10:00.000Z',
    nextDueAt: '2026-06-21T08:00:00.000Z',
    intervalDays: 1,
    ease: 1.85,
    lapses: 3,
    attempts: 6,
    correct: 2,
    missed: 4,
    streak: 0,
    due: true,
    lastResult: 'incorrect',
    lastRating: 'again',
    mastery: 18,
  },
};

export const openingNotesById: OpeningNoteStore = {
  'note-qga-root': {
    id: 'note-qga-root',
    openingId: 'qga-white-main',
    nodeId: 'qga-4-e3',
    body: 'Do not hurry Bxc4 before e3. The point is stable recovery, not pawn grabbing.',
    createdAt: '2026-06-18T10:00:00.000Z',
    updatedAt: '2026-06-20T12:20:00.000Z',
  },
  'note-italian-root': {
    id: 'note-italian-root',
    openingId: 'italian-black-classical',
    nodeId: 'italian-bc5',
    body: 'After c3, remember Nf6 before committing the d-pawn.',
    createdAt: '2026-06-19T16:45:00.000Z',
    updatedAt: '2026-06-19T16:45:00.000Z',
  },
};

export const importedOpeningLines: ImportedOpeningLine[] = [
  {
    id: 'import-qga-sample',
    name: "Queen's Gambit Accepted sample import",
    rawPgn: '1. d4 d5 2. c4 dxc4 3. Nf3 Nf6 4. e3 e6 5. Bxc4 Bd6 6. O-O O-O',
    moves: ['d4', 'd5', 'c4', 'dxc4', 'Nf3', 'Nf6', 'e3', 'e6', 'Bxc4', 'Bd6', 'O-O', 'O-O'],
    tags: ['Opening', 'Imported', 'Queen\'s Gambit'],
    errors: [],
    importedAt: '2026-06-21T09:00:00.000Z',
  },
];
